name: Swift Lint 

on:
  push:
    branches: [development, main]
  pull_request:
    branches: [development, main]

jobs:

  swiftlint:
    runs-on: ubuntu-20.04

    steps:
      - name: Clone Repo 
        uses: actions/checkout@v2

      - name: SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
            args: --strict
